### ISSUE TITLE
Prepare slides and script for presentation

### ISSUE THREAD

**Issue by djbpitt** [djbpitt/balisage_2017#10]
Total of 45 minutes, typically 30 minutes of presentation and 15 of discussion.

**Comment by djbpitt** [comment]
**reveal.js** creates slides in HTML/CSS: <http://lab.hakim.se/reveal-js/#/>
Can create concepts in DITA (each slide is a DITA concept, chaining file is a DITA map) and use DITA Open Toolkit inside \<oXygen/\> to  convert to reveal.js presentation. See <http://www.scriptorium.com/2012/11/creating-a-dita-ot-plugin-for-slides/> and <https://doctales.atlassian.net/wiki/spaces/reveal>.

**Comment by rhdekker** [comment]
After the not so successful experiment with Dita I suggest we use Markdown in combination with Pandoc and Reveal.JS or another HTML presentation framework instead. RMarkdown in RStudio can be used an IDE with preview functionality.

**Comment by djbpitt** [comment]
I created a placeholder presentation template in a new **presentation** subdirectory. There’s a **create_slides** shell script that runs the transformation. I'll add real content later. Of the five formats supported by Pandoc, slidy seemed the cleanest.

**Comment by djbpitt** [comment]
@rhdekker All images added to slide set except for intradocumentary variation. Add variant graph image from Elli and Ronald's work?

**Comment by djbpitt** [comment]
Done
