### ISSUE TITLE
comments and questions on paper draft

### ISSUE THREAD

**Issue by ebeshero** [djbpitt/balisage_2017#11]
## Comments 
* Infelicitous phrasing: “Below we offer examples of where text is not only not hierarchical (not just not mono-hierarchical, but sometimes not hierarchical at all), but also where it is not ordered,”
suggested rewording: “Below we offer examples of text that lacks hierarchy and also that lacks order. These examples are not just mono-hierarchical but sometimes not hierarchical at all. 

* Rephrase? “Nodes and (hyper)edges have types, and may also have other properties.”
suggested rewording: Nodes and (hyper)edges may have properties (like attributes in XML) such as types. 

* General comment: I like the paragraph-quotation vs. quotation-paragraph example to demonstrate how TAG doesn’t make one necessarily **”consist of”** the other. The simplicity of that phrasing makes me wonder about how we understand syntactical dependencies generally…

* Admirably phrased: Definition of overlap acc. to TAG:
“In the set-based terminology of TAG, overlap describes a relationship between sets where there is a non-empty intersection and neither set is a subset of the other.”
:-)

* On Discontinuity you write: 
“TAG, then, views fragmentation that must be reunited as an undesirable side-effect of the XML, GODDAG, and LMNL models, and regards linearly discontinuous content as a single item that may be separated when necessary, such as for serialization in LMNL sawtooth syntax, rather than as two objects that may be united when necessary.”
—In trying to wrap my head around this, I’m thinking of your explanation of TexMECS syntax: that it applies suspend and resume tags. (We’ve done something similar in modeling interrupted passages of speech in Amadis in XML, using attribute values on self-closing anchor elements, and I suppose you’d consider such signposting to be breakage—except here I want to point out that it’s not really interrupting a hierarchy, just signaling the moments of disruption and making it possible to be *parsed around* when we want to count spoken word tokens. I'm taking issue here with the idea that the interruption is *necessarily* meaningless or "not really there", because the text itself definitely shows discontinuity in its deliberate sequencing. Our reuniting here (by means of markup, whether TAG or TexMECS or milestone-style XML), makes it possible for us *to pretend as if the interruption never occurred*, which is often useful when you want to separate spoken words from words describing a speaking process, to be sure. I'm not objecting to the practice, but I'd like you to reconsider whether discontinuity is necessarily meaningless.

Certainly if you're going to cite only "she thought" and "he said" examples, discontinuity is going to *look* meaningless. But sometimes it's quite meaningful, and has a part to play in our connection of ideas. For example, there ought to be a difference in the way we read:

“Of course it wasn’t the same person,” she thought, and then looked at the picture again, ‘but no, there’s that mole above the eyelid!”
vs.
“Of course it wasn’t the same person, but no, there’s that mole above the eyelid!”  she thought, and then looked at the picture again.

My point is, *sometimes* discontinuity isn’t spurious, and in the hands of artful writers, discontinuities matter for all kinds of reasons: meter, tone, pattern, semantics. Discontinuity is, therefore, a property of text, and in modeling it, perhaps we shouldn’t presuppose in all cases that it doesn’t matter / is arbitrary. To presume that two fragments constitute a "single" item *first* might be just as problematic as to presume the sets are separated.

I suggest, then, that TAG should permit modeling in EITHER way, agnostically rather than presuming to treat all discontinuities as if they didn’t exist/didn’t matter. From what I'm reading here, I don't think you're going to have a problem with this--it's all a matter of how humans decide to constitute sets and mark disruptions and sequencing. I think your prose in the paper at this point may be pushing an exaggerated binary opposition against the other forms of markup/document modelling that you want to dissent with. That's the sort of thing that happens, of course, when you want to advance a new idea in opposition to all that came before, but I really think the language here could stand to be scaled back--you don't need to be so very much at odds with "flat" encoding, and you are, indeed, adding dimension that those other encodings are striving to signal in their own way. At the very least, TAG shouldn't itself have a "view" of the meaning of discontinuity--that's a strange anthropomorphism, since it should be the human encoder who figures that out. 

* I like the Scope of Reference section—helps explain how differently annotations *set* in relation to what they annotate (vs.anchored notes in XML)

* The TAG in Alexandria section sits awkwardly here b/c it isn’t finished…What seems a little strange in the material present is that the emphasis seems to be on export format with start and end tags—and it sounds like we’re ending the section on a note of XML?  (Why? Is it b/c that’s the most “useful” output in the absence of a syntax of TAG?)

* Alas, the text nodes of “Snark” are not easy to see in Appendix C, though the data structure is somewhat clear…b/c I can’t see the text, I forget what’s going on around the Baker that was so exciting when we last talked about it… Can the image resolution be improved--or can you make it possible to zoom this? 

## Questions:
* How would one query TAG? (I know, a syntax language, and you don’t have it, but can we speculate about what would be needed a little?) What does *traversing* a document (like “The Hunting of the Snark”) look like, if one were, say, seeking intersections among sets, or to collect all members of particular group?

* I wonder whether the strict sequenced order of text nodes sets the conditions for “parsing”? Can you forecast a little how a syntax for TAG might look?

**Comment by djbpitt** [comment]
Fixed.
