### ISSUE TITLE
Proposal to change "intratextual" to "intradocumentary"

### ISSUE THREAD

**Issue by bleekere** [djbpitt/balisage_2017#17]
I would propose the terms "inter-documentary" and "intra-documentary" instead of "intratextual" (and consequently "intertextual"). The main reason for this, is that the term "intertextuality" has a different connotation in literary studies and can therefore be confusing. From the point of genetic criticism one can differentiate between variation *within* the same document, or variation *across* different documents. 

While the discussion here is indeed about _textual_ variation, I think using the term intra-documentary will be more straightforward. Within genetic editing, at least, it is understood that this refers to textual variation on a document (often also described as "layers of text" although I can see that in the context of this paper this last description would only add to the confusion).

See also: http://www.tei-c.org/Activities/Council/Working/tcw19.html#alterations

**Comment by bleekere** [comment]
Here's a link to a google doc with some suggestions for the paragraph on intradocumentary/-textual variation: https://docs.google.com/document/d/12UmvR6OBF0-cT0p9FFT60-e1hwJRJtqQNre0CWbPT5g/edit?usp=sharing
Note: the paragraph is in the drafting phase but may help to get the discussion going.

**Comment by djbpitt** [comment]
Done!
