### ISSUE TITLE
Bibliography includes works that we don't cite

### ISSUE THREAD

**Issue by djbpitt** [djbpitt/balisage_2017#7]
We'll probably want to find a way to cite them, but if not, we might prefer to comment them out instead of deleting them, since that will make it easier to revisit the decision later.

**Comment by rhdekker** [comment]
Commented out all the bio entries that we don't cite. sperberg_2008-bielefeld is strange. The XSLT stylesheet does not create a link, but we do actually reference that slideshow in the paper. Commenting out that entry causes an error.

**Comment by djbpitt** [comment]
Done
