### ISSUE TITLE
Simultaneity, partially ordered sets, and acyclic directed multigraphs

### ISSUE THREAD

**Issue by djbpitt** [djbpitt/balisage_2017#9]
We describe simultaneity as a partially ordered set, but might it not be described instead (or additionally) as an acyclic directed multigraph (https://en.wikipedia.org/wiki/Multigraph)?

**Comment by rhdekker** [comment]
It is both a partially ordered set and a directed multigraph. I do however have my doubt about the acyclic aspect. That is true in the example that you give in that section, but if we go to the next section and add transpositions to the mix then the graph will become cyclic and the acyclic aspect will be gone.

**Comment by djbpitt** [comment]
I clarified, below the transposition example, that following only labeled edges permitted traversal without cycles, with the idea that this refers to how how labeling helps mitigate the challenge of cycles, without saying that the graph isn't cyclic. If this looks okay to you, at least for now, we can close the issue; if not, let's talk about how to clarify it further.

**Comment by djbpitt** [comment]
Fixed (rhd/djb Skype call 2017-06-18)
